import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/catppuccin.toml"
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.9

padding.x = 20
padding.y = 20

option_as_alt = "Both"
