local input_source = require("modules.input_source")
local mission_control = require("modules.mission-control")
local app_shortcut = require("modules.app-shortcut")
local exosphere = require("modules.exosphere")
local seeklick = require("modules.seeklick")

input_source.setup()
mission_control.setup()
app_shortcut.setup()
exosphere.setup_exosphere_automation()
seeklick.setup()
