include themes/catppuccin-macchiato.conf

shell_integration enabled

font_family family="Google Sans Code" style=Light wght=300 MONO=1
font_size 12
text_composition_strategy 1.0 0
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFD,U+100000-U+10FFFD Hack Nerd Font
symbol_map U+1100-U+11FF,U+3130-U+318F,U+A960-U+A97F,U+AC00-U+D7AF,U+D7B0-U+D7FF D2Coding

cursor #d3cdc3
cursor_text_color background
cursor_shape block
cursor_trail 1
cursor_trail_decay 0.04 0.16
cursor_trail_start_threshold 2

background_opacity 1.0
background_blur 32

macos_option_as_alt both
hide_window_decorations titlebar-only

strip_trailing_spaces smart
window_padding_width 0
placement_strategy center

map cmd+v paste_from_clipboard
map ctrl+shift+v paste_from_clipboard
map alt+backspace send_text all \e\x7f
map alt+left send_text all \eb
map alt+right send_text all \ef
map alt+1 send_text all \e1
map alt+2 send_text all \e2
map alt+3 send_text all \e3
map alt+4 send_text all \e4
map alt+5 send_text all \e5
map alt+6 send_text all \e6
map alt+7 send_text all \e7
map alt+8 send_text all \e8
map alt+9 send_text all \e9
map ctrl+semicolon send_text all \e[59;5u
map shift+enter send_text all \e[13;2u
map cmd+left send_key home
map cmd+right send_key end
map cmd+up send_key home
map cmd+down send_key end
